workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        GRADLE_OPTS: "-Xmx4096m"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      

    

