workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 120
    instance_type: mac_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        GRADLE_OPTS: "-Xmx4096m" # Fixes Java heap space issue
    scripts:
      - name: Pre-build
        script: |
          echo "Running pre-build steps..."
          flutter pub get
      - name: Build Android
        script: |
          flutter build apk --flavor android-production -t lib/main.dart
      - name: Build iOS
        script: |
          flutter build ios --flavor ios-production -t lib/main.dart --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-*-release.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        on_build_success: true
